# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    # Run tests for any PRs.
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v1

        - name: SSH into server and pull + build & run docker
        uses: appleboy/ssh-action@master

        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
        
            run: npm install -g yarn
            - name: yarn install, build, and test
                run: |
                yarn
                yarn build --if-present
                yarn test
